### PR TITLE
Don't return the error inside of the callback

### PR DESCRIPTION
**Pull request by okdistribute**
or else there are two response headers sent when there's an error. fixes

### CODE REVIEW

**Comment by okdistribute** [comment]
fixes #56 and #59

**Comment by hackergrrl** [comment]
Nice catch! :horse: LGTM

**Comment by okdistribute** [comment]
OK @noffle i resolved the conflict

**Comment by hackergrrl** [comment]
Still looks good!

**Comment by redconfetti** [comment]
Thanks for contributing this fix @karissa

**Pull request merged**
